// Generated by CoffeeScript 1.3.1
(function()	{
	$(function() {
		var base64, check, checksum, deflated, encoded, input;
		checksum = function(string) {
			var chk, chr, i;
			chk = 0;
			for (i in string) {
				chr = string[i];
				chk += chr.charCodeAt(0) * (i + 1);
			}
			return chk % 10;
		};
		$('#save-button').click(function() {
			var base64, check, deflated, encoded, input;
			input = $('#input-field').get(0).value;
			deflated = RawDeflate.deflate(input);
			base64 = Base64.toBase64(deflated);
			check = checksum(base64);
			encoded = base64 + check;
			return window.location = 'view.html#' + encoded;
		});
	});
}).call(this);