// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    var base64, deflated, input;
    $('#save-button').click(function() {
      var base64, deflated, input;
      input = $('#input-field').get(0).value;
      deflated = RawDeflate.deflate(input);
      base64 = Base64.toBase64(deflated);
      return window.location.hash = base64;
    });
    if (window.location.hash) {
      base64 = window.location.hash.replace(/^#/, '');
      deflated = Base64.fromBase64(base64);
      input = RawDeflate.inflate(deflated);
      return $('#input-field').get(0).value = input;
    }
  });

}).call(this);
